name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hello-service-build:
    name: Build Spring Boot Hello Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hello-service
    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  time-service-build:
    name: Lint & Build Time Service (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: time-service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint || echo "Lint failed"
      - name: Build Docker image
        run: docker build -t time-service .

  api-gateway-build:
    name: Lint & Build API Gateway (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-gateway
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint || echo "Lint failed"
      - name: Build Docker image
        run: docker build -t api-gateway .
